# Site settings
title: Nadia Lucas
email: nrlucas@uchicago.edu
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://nadialucas.com # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge


collections:
  home:
    output: true
    permalink: /home/:path/
  research:
    output: true
    permalink: /research/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
